name: Render library update

on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
  runs-on: ubuntu-latest
  if: "contains(github.event.head_commit.message, 'initial commit')"
  steps:
      run:
        Rscript -e "install.packages(c('tidyverse', 'plotly', 'RSocrata'))"
    - name: Render index.html
      uses: lc5415/rmarkdown-action@v1
      with: 
        input_file: index.Rmd
    output_format: html_document
    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add myplot.png
        git commit -m 'Re-build package plot' || echo "No changes to commit"
        git push origin || echo "No changes to commit"          