name: Render library update

on:
  schedule:
    - cron: "*/3 * * * *"

jobs:
  render:
    name: Render my document
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with: 
          r-version: '4.3.0'
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Install rmarkdown and tidyverse
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "tidyverse"))'
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("index.Rmd", output_format = "all")'
      - name: Commit results
        run: |
          git add index*
          git commit -m 'Re-build my-document' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
